{% set name = "unidock" %}
{% set version = "1.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dptech-corp/Uni-Dock/archive/refs/tags/{{ version }}.tar.gz
  sha256: 0799f7673ac7d4151ced6a1f7bf670b8d3e78032192f304b6750527c1b0016e5

build:
  skip: true  # [not linux]
  skip: true  # [cuda_compiler_version == "None"]
  script: |
    cd unidock_tools
    pip install . -vv
    cd ..
    cd unidock
    mkdir conda_build
    cd conda_build
    cmake ${CMAKE_ARGS} ${SRC_DIR}/unidock
    make unidock -j$CPU_COUNT
    make install
  string: cuda{{ cuda_compiler_version | replace('.', '') }}_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - {{ compiler('cuda') }}
    - cmake
    - make
    - libgomp
  host:
    - python
    - pip
    - setuptools
    - libboost-devel
    - libcurand-dev  # [(cuda_compiler_version or "").startswith("12")]
  run:
    - python
    - MDAnalysis
    - networkx
    - numpy
    - pandas
    - pathos
    - rdkit

test:
  commands:
    # Dry run to verify dynamic libs are present.
    - unidock --version
    - unidocktools --help

about:
  home: https://github.com/dptech-corp/Uni-Dock
  doc_url: https://github.com/dptech-corp/Uni-Dock
  dev_url: https://github.com/dptech-corp/Uni-Dock
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: unidock/LICENSE
  summary: A GPU-accelerated molecular docking program
  description: >
    Uni-Dock is a GPU-accelerated molecular docking program developed by DP Technology. It supports various scoring functions including vina, vinardo, and ad4. Uni-Dock achieves more than 1000-fold speed-up on V100 GPU with high-accuracy, compared with the AutoDock Vina running in single CPU core. The paper has been accepted
    by JCTC (doi: 10.1021/acs.jctc.2c01145).

extra:
  recipe-maintainers:
    - caic99
